### ISSUE TITLE
difficulty on understanding suggestion

### ISSUE THREAD

**Issue by RahulPrashar-140898** [kishan0725/Movie-Recommendation-System-with-Sentiment-Analysis#3]
Sir can u please explain   how are u moving Suggestions(which includes data for autocompletion) from main.py  to your html as you don't seem to pass in along render function as parameters.

**Comment by kishan0725** [comment]
@RahulPrashar-140898 This repo is a kind of an outdated one. So, kindly take a look at this repo - https://github.com/kishan0725/AJAX-Movie-Recommendation-System-with-Sentiment-Analysis
