### ISSUE TITLE
TypeError: Object of type Undefined is not JSON serializable 

### ISSUE THREAD

**Issue by amanattar** [kishan0725/Movie-Recommendation-System-with-Sentiment-Analysis#6]
this issue is showing on templates\home.html", line 62, in top-level template code
var films = {{suggestions|tojson}};

**Comment by kishan0725** [comment]
Make sure you have the list of suggested movies in the 'suggestions' variable

**Comment by amanattar** [comment]
yes it is in suggestions variable but it still showing the error.
i clone your repository i dont modify any thing

**Comment by kishan0725** [comment]
For those who are going through this similar issue, the issue has been resolved in this PR - #7
